version: '3.9'

services:
  db:
    image: postgres
    container_name: kpa-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontknow
      POSTGRES_DB: kpa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build: .
    container_name: kpa-fastapi
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
